defmodule OtlpShipper.Conformance.TraceOutput do
  @moduledoc false
  @service "service.name: Str(otlp-shipper-conformance)"
  @resource_schema "Resource SchemaURL: https://otlp-shipper.dev/conformance/resource"
  @scope_schema "ScopeSpans SchemaURL: https://otlp-shipper.dev/conformance/scope"
  @scope "InstrumentationScope conformance.sdk 1.0"

  @doc false
  @spec verify(String.t()) :: :ok | {:error, :collector_trace_output_mismatch}
  def verify(output) when is_binary(output) and byte_size(output) <= 10_000_000 do
    records = parse(output)
    spans = Enum.filter(records, &(&1.type == :span))
    named = Map.new(spans, &{field(&1, "Name"), &1})

    with 3 <- length(spans),
         %{
           "otlp-shipper-conformance-root" => root,
           "otlp-shipper-conformance-child" => child,
           "otlp-shipper-conformance-remote" => remote
         } <- named,
         true <- Enum.all?(spans, &valid_span?/1),
         true <- valid_relationships?(root, child, remote),
         true <- valid_child?(child),
         true <- Enum.any?(records, &correlated_log?(&1, child)) do
      :ok
    else
      _ -> {:error, :collector_trace_output_mismatch}
    end
  end

  def verify(_), do: {:error, :collector_trace_output_mismatch}

  # Track resource/scope ownership instead of accepting matching text elsewhere.
  defp parse(output) do
    state = %{resource: [], scope: [], scoped: false, current: nil, records: []}

    output
    |> String.split("\n")
    |> Enum.reduce(state, &consume/2)
    |> flush()
    |> Map.fetch!(:records)
  end

  # Collector prefixes resource headings with its timestamp and logger fields.
  defp consume(line, state) do
    cond do
      Regex.match?(~r/(?:^|\t)Resource(?:Spans|Log|Metrics) #\d+$/, line) ->
        %{flush(state) | resource: [], scope: [], scoped: false}

      Regex.match?(~r/^Scope(?:Spans|Logs|Metrics) #\d+$/, line) ->
        %{flush(state) | scope: [], scoped: true}

      Regex.match?(~r/^Span #\d+$/, line) ->
        start_record(state, :span)

      Regex.match?(~r/^LogRecord #\d+$/, line) ->
        start_record(state, :log)

      state.current != nil ->
        update_in(state.current.lines, &[line | &1])

      state.scoped ->
        %{state | scope: [line | state.scope]}

      true ->
        %{state | resource: [line | state.resource]}
    end
  end

  # Snapshot each record's enclosing identity before collecting its own fields.
  defp start_record(state, type) do
    state = flush(state)
    %{state | current: %{type: type, resource: state.resource, scope: state.scope, lines: []}}
  end

  # Finish the current record before changing its enclosing resource or scope.
  defp flush(%{current: nil} = state), do: state
  defp flush(state), do: %{state | records: [state.current | state.records], current: nil}

  # Scalar fields exclude attribute arrows and event names with the same label.
  defp field(record, key) do
    pattern = Regex.compile!("^\\s*" <> Regex.escape(key) <> "\\s*:\\s*(.*?)\\s*$")

    Enum.find_value(scalar_lines(record), fn line ->
      case Regex.run(pattern, line) do
        [_, value] -> value
        _ -> nil
      end
    end)
  end

  # A nested event or link cannot supply a missing scalar field on its parent span.
  defp scalar_lines(%{type: :span} = span) do
    span
    |> sections()
    |> Enum.find_value(fn
      {:span, lines} -> Enum.reverse(lines)
      _ -> nil
    end)
  end

  defp scalar_lines(record), do: Enum.reverse(record.lines)

  # Preserve section ownership when Collector renders nested events and links.
  defp sections(span) do
    span.lines
    |> Enum.reverse()
    |> Enum.reduce([{:span, []}], &section_line/2)
  end

  # Headers start a new bounded section; following attributes belong only to it.
  defp section_line(line, [{kind, lines} | rest] = sections) do
    case String.trim(line) do
      "SpanEvent #" <> _ -> [{:event, []} | sections]
      "SpanLink #" <> _ -> [{:link, []} | sections]
      "Events:" -> [{:event_header, []} | sections]
      "Links:" -> [{:link_header, []} | sections]
      _ -> [{kind, [line | lines]} | rest]
    end
  end

  # Normalize only indentation and debug attribute arrows, preserving exact values.
  defp contains?(lines, expected) do
    actual = MapSet.new(lines, &(String.trim(&1) |> String.replace_prefix("-> ", "")))
    Enum.all?(expected, &MapSet.member?(actual, &1))
  end

  # Require each span to carry its own expected envelope and valid identity.
  defp valid_span?(span) do
    contains?(span.resource, [@service, @resource_schema]) and
      contains?(span.scope, [@scope, @scope_schema]) and
      identity?(field(span, "Trace ID"), 32) and identity?(field(span, "ID"), 16) and
      is_binary(field(span, "Start time")) and is_binary(field(span, "End time"))
  end

  # Root/child IDs are generated by the SDK; only their actual relationships matter.
  defp valid_relationships?(root, child, remote) do
    field(root, "Parent ID") in ["", "0000000000000000"] and
      field(root, "Kind") == "Internal" and field(child, "Kind") == "Client" and
      field(root, "Trace ID") == field(child, "Trace ID") and
      field(root, "ID") == field(child, "Parent ID") and field(root, "ID") != field(child, "ID") and
      valid_remote?(remote, root)
  end

  # The remote fixture must retain both identifiers from its incoming context.
  defp valid_remote?(remote, root) do
    field(remote, "Kind") == "Server" and field(remote, "Parent ID") == "0000000000000042" and
      field(remote, "Trace ID") == "00000000000000000000000000000043" and
      field(remote, "Trace ID") != field(root, "Trace ID")
  end

  # Status and event assertions are tied to the intended child, never a decoy span.
  defp valid_child?(child) do
    field(child, "Status code") == "Error" and
      field(child, "Status message") == "synthetic failure" and
      contains?(scalar_lines(child), ["conformance.span: Bool(true)"]) and event?(child)
  end

  # The expected name and attribute must occur in the same event section.
  defp event?(child) do
    child
    |> sections()
    |> Enum.any?(fn
      {:event, lines} ->
        contains?(lines, ["Name: conformance-event", "conformance: Bool(true)"])

      _ ->
        false
    end)
  end

  # The synthetic log must identify the actual child span and enclosing service.
  defp correlated_log?(%{type: :log} = log, child) do
    contains?(log.resource, [@service]) and
      field(log, "Body") == "Str(otlp-shipper-conformance-log)" and
      field(log, "Trace ID") == field(child, "Trace ID") and
      field(log, "Span ID") == field(child, "ID")
  end

  defp correlated_log?(_, _), do: false

  # Reject zero, malformed, and prefix-matching identities.
  defp identity?(value, width) when is_binary(value),
    do:
      byte_size(value) == width and Regex.match?(~r/\A[0-9a-f]+\z/, value) and
        value != String.duplicate("0", width)

  defp identity?(_, _), do: false
end
